spin_manifest_version = 2

[application]
name = "spin-regist-service"
version = "0.1.0"
description = "Go WASM user registration service with Dapr sidecar"

[[trigger.http]]
route = "/..."
component = "spin-regist-service"

[component.spin-regist-service]
source = "main.wasm"
allowed_outbound_hosts = [
    "http://127.0.0.1:3517",
]
[component.spin-regist-service.build]
command = "tinygo build -target=wasip1 -buildmode=c-shared -no-debug -o main.wasm ."
watch = ["**/*.go", "go.mod"]
