spin_manifest_version = 2

[application]
name = "spin-go-app"
version = "0.1.0"
authors = ["aGentleKnife <1793575354@qq.com>"]
description = "Go WASM app with Dapr sidecar"

[[trigger.http]]
route = "/..."
component = "spin-go-app"

[component.spin-go-app]
source = "main.wasm"
allowed_outbound_hosts = [
    "http://127.0.0.1:3500",
]
[component.spin-go-app.build]
command = "tinygo build -target=wasip1 -buildmode=c-shared -no-debug -o main.wasm ."
watch = ["**/*.go", "go.mod"]
